### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by worldwidemisery** [jasperLove/jasper.rip#1]
user interface
- [x] upload global addon profiles.
- [ ] upload priest
- [x] upload monk
- [x] upload warlock
- [x] upload demon hunter
- [x] upload paladin
- [x] upload mage
- [ ] bug fix priest
- [x] bug fix demon hunter
- [ ] m+ auras
- [ ] fork or make timer (some1 wanna do this 4 me? please)

priest
- [x] power infusion cooldown showing incorrectly
- [ ] power of the dark side procs acting strange
